// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.Database.Data;

#nullable disable

namespace Notes.Database.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20250416165155_InitialCreate")]
    partial class InitialCreate
    {
        // Remove the BuildTargetModel override completely
    }
}
